<h1><strong>Electronic Nicotine Delivery Systems (Electronic Cigarettes)</strong></h1>
<p>The American Lung Association is very concerned about the potential health consequences of electronic cigarettes as well as the unproven claims that they can be used to help smokers quit. Also unknown is what the potential harm may be to people exposed to secondhand emissions from e-cigarettes.</p>
<p>Even more alarming, <a href="http://www.lung.org/press-room/press-releases/tobacco-control/NYTS-shows-youth-ecig-tripled.html" target="_blank">e-cigarette use among high school and middle school students tripled from 2013 to 2014</a> and now more youth use e-cigarettes than any other tobacco product.</p>
<p>Almost all states have approved laws that prohibit the sale of some or all e-cigarettes to minors. As part of these laws, most of the states have defined e-cigarettes as something other than tobacco products – something the e-cigarette industry has been promoting. Several states have also extended their smokefree workplace laws to include e-cigarettes.</p>
<p>See the U.S. maps below for more information on which states have taken action concerning e-cigarettes.</p>
<ul>
<li><a href="http://www.lungusa2.org/slati/reports/ecigarette-sales-to-minors-laws-2015.pdf" target="_blank">Map of States that have Prohibited Sales of E-Cigarettes to Minors &ndash; by Type</a></li>
<li><a href="http://www.lungusa2.org/slati/reports/e-cigarette-smokefree-map-2015.pdf" target="_blank">Map of States that have Prohibited the Use of E-Cigarettes in Public Places and Workplaces</a></li>
</ul>
<p>The U.S. Food and Drug Administration has also issued a proposed rule that would assert the agency&rsquo;s authority of all tobacco products, including e-cigarettes. You can read more information on this <a href="http://www.fda.gov/TobaccoProducts/Labeling/ucm388395.htm" target="_blank">here</a>. The American Lung Association filed <a href="http://www.lung.org/get-involved/advocate/advocacy-documents/comments-to-the-fda-re.pdf" target="_blank">extensive comments</a> as well as another set of comments <a href="http://www.lung.org/get-involved/advocate/advocacy-documents/comments-to-fda-from-partners.pdf" target="_blank">with partners</a> in response.</p>